### ISSUE TITLE
AGESA 1.2.0.8 added curve optimizer in BIOS

### ISSUE THREAD

**Issue by tutyamxx** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#14]
You might want to update this readme. PBO2 is not needed anymore

**Comment by JoraeMC** [comment]
Of course PBO2 Tuner is still needed. Agesa 1.2.0.8 is still not mass available, just one or two premium boards of each manufacturer had the beta or released Bios including 1.2.0.8. Also, if you didn't know from 1.2.0.7 some vendors like MSI include some form of Curve Optimizer for 5800x3d, it's named Kombo Strike. But I'm pretty convinced that still with 1.2.0.8 around is not sure to have the CO option for mid or low end boards, it depends totally on the manufacturer.

**Comment by tutyamxx** [comment]
Ah you're right.
