### ISSUE TITLE
inpoutx64sys blockt by vanguard

### ISSUE THREAD

**Issue by Slimmer2** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#16]
The file inpoutx64.sys was blocked by vanduard. 
![Screenshot_20230115_144947](https://user-images.githubusercontent.com/8680824/212548162-04a74087-3bc2-4e6c-bf8e-e4ee9c16c6c5.png)

**Comment by tutyamxx** [comment]
It is blocked because that is a tool/library/api that detects board stats. Vanguard doesn't like that so it blocks it. It's fine

**Comment by 0verthink** [comment]
> 

will the undervolt still work with vanguard blocking it?

**Comment by 0verthink** [comment]
> It is blocked because that is a tool/library/api that detects board stats. Vanguard doesn't like that so it blocks it. It's fine

will the undervolt still work with vanguard blocking it?

**Comment by tutyamxx** [comment]
Yes. It only uses a couple of power readings and mostly SMU status.

**Comment by tutyamxx** [comment]
However it will work only with curve. If you change the voltage it won't
work.
