### ISSUE TITLE
Automating start up not working (windows 11 pro) 

### ISSUE THREAD

**Issue by rand-star** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#17]
I don't know task scheduler password and I've tried googling a bunch spent hours and couldn't make it work. Ran as administrator etc.

Also did another method where you make a shortcut and put it like this: "C:\Users\user\Desktop\pbo2\PBO2 tuner.exe" -30 -30 -30 -30 -30 -30 -30 -30
Then you put that shortcut with the command in startup folder but it doesn't work unless you turn some stuff off in regedit which messes with some games I play so I can't do that. 

I have very old motherboard so I believe I can't do anything there (aorus b450 elite) 

Only thing that works is me manually clicking the shortcut. It's the weirdest thing and it really frustrates me. I don't know why I cant use task manager. I only have 1 user and it's obviously an admin but I still need a password I've tried my login code I've tried my microsoft login. 

I saw somebody on youtube say that you can make a bat file that executes the PBO2 shortcut with the -30's and then put a shortcut to that bat file in the startup folder but couldn't figure out how to do that either. 

Thanks in advance

**Comment by RoyRiv3r** [comment]
Try to create a shortcut and elevate it with Winaero Tweaker so you don't need to execute it with UAC, place it in the C:\Users\<name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup, and you're done

**Comment by rand-star** [comment]
> Try to create a shortcut and elevate it with Winaero Tweaker so you don't need to execute it with UAC, place it in the C:\Users<name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup, and you're done

Hey this works for me tysm!! I will share with others :)
This is how I did it https://imgur.com/a/JqsYojR and then place that shortcut in startup folder
