### ISSUE TITLE
Download link no longer works in the thread

### ISSUE THREAD

**Issue by kThayer2** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#2]
Can no longer download pbo2 from link mentioned on forum.
![image](https://user-images.githubusercontent.com/6999856/180609436-7461dcb0-2d37-4eeb-a928-364e92a576af.png)

**Comment by zDEFz** [comment]
Hey, I still have a copy if you'd like. Other than that - ASUS is going to get PBO2 access in roundabout 2 months.

**Comment by PrimeO7** [comment]
There seems to be a new download link for a beta version of pbo2. 
https://www.overclock.net/threads/5800x3d-owners.1798046/page-85#post-29009118

Let me know if everything still works!

**Comment by PrimeO7** [comment]
New link to the updated Version (not Beta):

https://www.overclock.net/threads/corecycler-tool-for-testing-curve-optimizer-settings.1777398/page-45#post-28999750
