### ISSUE TITLE
Great guide.

### ISSUE THREAD

**Issue by dongerlel** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#23]
This guide is great but why not just set it once in UEFI and call it a day?

**Comment by PrimeO7** [comment]
https://github.com/PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#2-why-are-we-doing-it-what-are-the-benefits

**Comment by dongerlel** [comment]
on asrock b550 pro 4 eveything is unlocked if anyone is wondering
