### ISSUE TITLE
debug-cli link not working

### ISSUE THREAD

**Issue by Benik3** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#27]
Link to the overclock.net forum is dead. Link to the tool should be pointed here: https://github.com/sp00n/corecycler
edit: Hmm it looks like whole overclock.net forum is not working

**Comment by PrimeO7** [comment]
The link is working fine.

**Comment by Benik3** [comment]
True, it was problem of whole forum.
Anyway latest version of PBO Tuner: 
https://drive.google.com/file/d/17UZ7pXpc85GXfJiqDlYLoEuYw38vIsuk/view  
https://www.overclock.net/threads/official-amd-5700g-5600g-5300g-apu-apu.1792840/page-27#post-29121806

Unfortunately PJVol doesn't have any place where we can find easily the latest version...
