### ISSUE TITLE
undervolting 5800x3d 

### ISSUE THREAD

**Issue by KhaledElSaiad** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#6]
i'm trying to do undervolting 5800x3d with pbo2 but it's not working at all i tried from -5 to -50 but nothing
idle is 43 under load is 90 cb r23
 
it's like it's not applying the setting i enter the only thing that works is on the limits > temp limit i can set it to 80 and it apply and work anything else is not working,i did flash back to bios 4006 and tried but got nothing my specs are
asus viii ch hero wifi
bios 4201
lian li galahad 360
32 gb crucial ballistix ram 3600mhz
asus 3080 ti
win 10
everything is up to date

**Comment by PrimeO7** [comment]
what agesa version were you on before flashing back? this should normally work on all bios versions ?

**Comment by KhaledElSaiad** [comment]
ComboV2PI 1207
