### ISSUE TITLE
Cant get limits to apply with Task Scheduler

### ISSUE THREAD

**Issue by JarekLB** [PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner#7]
everything works perfectly except I can't get the PPT TDC and EDC settings to apply with the task scheduler.

here's an [Image ](https://imgur.com/iDQNaJN)of how I can it configured

**Comment by anibalpedraza** [comment]
You have to add an extra 0 to the parameters.

The program, when providing more than 8 arguments, expects exactly 4 more arguments: PPT, TDC, EDC and Max Frequency. Putting a 0 in the last one keeps the default value.
